export type FunctionalCategory =
  | 'Antiklontermiddel'
  | 'Antioxidant'
  | 'Antischuimmiddel'
  | 'Bevochtigingsmiddel'
  | 'Complexvormer'
  | 'Conserveermiddel'
  | 'Contrastverhoger'
  | 'Drijfgas'
  | 'Draagstof'
  | 'Emulgator'
  | 'Geleermiddel'
  | 'Gemodificeerd zetmeel'
  | 'Glansmiddel'
  | 'Kleurstof'
  | 'Meelverbeteraar'
  | 'Rijsmiddel'
  | 'Schuimmiddel'
  | 'Smaakversterker'
  | 'Smeltzout'
  | 'Stabilisator'
  | 'Verdikkingsmiddel'
  | 'Verpakkingsgas'
  | 'Verstevigingsmiddel'
  | 'Voedingszuur'
  | 'Vulstof'
  | 'Zoetstof'
  | 'Zuurteregelaar';
