import type { FunctionalCategory } from '@picklist/types';

export interface ENumberDefinition {
  // Official identification
  code: string;
  officialName: string;
  dutchNames?: string[];

  // Functional classification
  functionalCategory: FunctionalCategory;
  dutchCategoryName: string;
  purpose: string;

  // Safety and regulatory
  isNaturallyOccurring: boolean;
  isSynthetic: boolean;
  isAnimalDerived: boolean;
  organicPermitted: boolean;
  bannedSince?: string;

  // Special warnings
  southamptonSix: boolean;
  isAllergen: boolean;
  pkuWarning: boolean;
  asthmaEczemaRisk: boolean;

  // Consumer information
  commonProducts: string[];
  voedingscentrumGuidance: string;
}

export interface ConsumerGuidance {
  // Safety messaging (based on Voedingscentrum position)
  safetyMessage: string;
  officialPosition: string;

  // Warning templates
  childWarningTemplate: string;
  pkuWarningTemplate: string;
  allergenWarningTemplate: string;

  // Clean label alternatives
  naturalAlternatives: Record<string, string>;
  dutchPreferredNames: Record<string, string>;

  // Educational content
  categoryExplanations: Record<FunctionalCategory, string>;
  commonMisconceptions: string[];
}

// Most common E-numbers from research (E330: 1,726×, E202: 1,156×, E300: 1,053×)
export const E_NUMBER_DATABASE: Record<string, ENumberDefinition> = {
  // Colors (E100-E199)
  E100: {
    code: 'E100',
    officialName: 'Curcumin',
    dutchNames: ['curcumine', 'kurkuma'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Gele kleurstof uit kurkuma',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['curry', 'mosterd', 'kaas'],
    voedingscentrumGuidance: 'Natuurlijke kleurstof uit kurkuma, veilig voor consumptie',
  },
  E102: {
    code: 'E102',
    officialName: 'Tartrazine',
    dutchNames: ['tartrazine'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Gele kleurstof',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: true,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['snoep', 'dranken', 'desserts'],
    voedingscentrumGuidance: 'Kan de activiteit of oplettendheid van kinderen nadelig beïnvloeden',
  },
  E104: {
    code: 'E104',
    officialName: 'Quinoline Yellow',
    dutchNames: ['chinolinegeel'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Gele kleurstof',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: true,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['snoep', 'ijs', 'dranken'],
    voedingscentrumGuidance: 'Kan de activiteit of oplettendheid van kinderen nadelig beïnvloeden',
  },
  E110: {
    code: 'E110',
    officialName: 'Sunset Yellow FCF',
    dutchNames: ['zonnegeel fcf', 'oranjegeel s'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Oranje kleurstof',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: true,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['snoep', 'dranken', 'desserts'],
    voedingscentrumGuidance: 'Kan de activiteit of oplettendheid van kinderen nadelig beïnvloeden',
  },
  E120: {
    code: 'E120',
    officialName: 'Cochineal',
    dutchNames: ['cochenille', 'karmin'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Rode kleurstof uit schildluizen',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: true,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['yoghurt', 'snoep', 'vleeswaren'],
    voedingscentrumGuidance:
      'Natuurlijke rode kleurstof, niet geschikt voor vegetariërs/veganisten',
  },
  E122: {
    code: 'E122',
    officialName: 'Azorubine',
    dutchNames: ['azorubine', 'karmozijn'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Rode kleurstof',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: true,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['snoep', 'dranken', 'desserts'],
    voedingscentrumGuidance: 'Kan de activiteit of oplettendheid van kinderen nadelig beïnvloeden',
  },
  E124: {
    code: 'E124',
    officialName: 'Ponceau 4R',
    dutchNames: ['ponceau 4r', 'cochenillerood a'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Rode kleurstof',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: true,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['snoep', 'dranken', 'desserts'],
    voedingscentrumGuidance: 'Kan de activiteit of oplettendheid van kinderen nadelig beïnvloeden',
  },
  E1400: {
    code: 'E1400',
    officialName: 'Modified starch',
    dutchNames: [
      'gemodificeerd zetmeel',
      'gemodificeerd maïszetmeel',
      'gemodificeerd maiszetmeel',
      'gemodificeerd maizetmeel',
      'gemodificeerd aardappelzetmeel',
    ],
    functionalCategory: 'Gemodificeerd zetmeel',
    dutchCategoryName: 'zetmeel',
    purpose: 'Gemodificeerd zetmeel, gebruikt als verdikkingsmiddel en stabilisator',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['sauzen', 'soepen', 'bakkerij'],
    voedingscentrumGuidance: 'Gemodificeerd zetmeel wordt veel gebruikt als verdikkingsmiddel',
  },
  E129: {
    code: 'E129',
    officialName: 'Allura Red AC',
    dutchNames: ['allurarood ac'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Rode kleurstof',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: true,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['snoep', 'dranken', 'desserts'],
    voedingscentrumGuidance: 'Kan de activiteit of oplettendheid van kinderen nadelig beïnvloeden',
  },
  E171: {
    code: 'E171',
    officialName: 'Titanium dioxide',
    dutchNames: ['titaniumdioxide'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Witte kleurstof',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    bannedSince: '2022-08-07',
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: [],
    voedingscentrumGuidance: 'verboden sinds augustus 2022 vanwege mogelijke DNA-schade',
  },

  // Emulsifiers / lecithins
  E322: {
    code: 'E322',
    officialName: 'Lecithin',
    dutchNames: [
      'lecithine',
      'lecithinen',
      'sojalecithine',
      'soja lecithine',
      'soja-lecithine',
      'sojalecithinen',
      'lecithinen soja',
      'zonnebloemlecithine',
      'zonnebloem lecithine',
      'zonnebloem-lecithine',
      'sunflower lecithin',
      'sunflower-lecithin',
      'sunflowerlecithin',
      'emulgator sojalecithine',
      'emulgator lecithinen',
    ],
    functionalCategory: 'Emulgator',
    dutchCategoryName: 'emulgator',
    purpose: 'Emulgator, stabiliseert vetten en verbetert textuur',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: true,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['chocolade', 'bakkerij', 'sauzen'],
    voedingscentrumGuidance: 'Veelgebruikte emulgator, kan van soja of eieren komen',
  },

  // Gums & thickeners
  E407: {
    code: 'E407',
    officialName: 'Carrageenan',
    dutchNames: ['carrageen', 'carrageenaan', 'carrageenan', 'carrageen (carrageen)'],
    functionalCategory: 'Stabilisator',
    dutchCategoryName: 'stabilisator',
    purpose: 'Verdikkingsmiddel en stabilisator uit rood zeewier',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['desserts', 'zuivel', 'vleeswaren'],
    voedingscentrumGuidance: 'Natuurlijk verdikkingsmiddel uit zeewier',
  },

  E412: {
    code: 'E412',
    officialName: 'Guar gum',
    dutchNames: ['guarpitmeel', 'guargom', 'guar gom'],
    functionalCategory: 'Stabilisator',
    dutchCategoryName: 'stabilisator',
    purpose: 'Verdikkingsmiddel uit guarpitten',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['bakkerij', 'sauzen', 'zuivel'],
    voedingscentrumGuidance: 'Natuurlijk verdikkingsmiddel, vaak vermeld als guarpitmeel',
  },

  E410: {
    code: 'E410',
    officialName: 'Locust bean gum / Carob bean gum',
    dutchNames: ['johannesbroodpitmeel', 'johannesbroodpitmeel (E410)', 'locust bean gum'],
    functionalCategory: 'Stabilisator',
    dutchCategoryName: 'stabilisator',
    purpose: 'Verdikkingsmiddel uit de zaden van de johannesbroodboom (carob)',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['ijs', 'sauzen', 'desserts'],
    voedingscentrumGuidance: 'Natuurlijk verdikkingsmiddel, vaak vermeld als johannesbroodpitmeel',
  },

  E415: {
    code: 'E415',
    officialName: 'Xanthan gum',
    dutchNames: ['xanthaangom', 'xanthan', 'xanthan gom', 'xanthaangom (xanthan)'],
    functionalCategory: 'Stabilisator',
    dutchCategoryName: 'stabilisator',
    purpose: 'Verdikkingsmiddel en stabilisator',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['sauzen', 'bakkerij', 'glutenvrije producten'],
    voedingscentrumGuidance: 'Veelgebruikt verdikkingsmiddel, vaak in kleine hoeveelheden',
  },

  E414: {
    code: 'E414',
    officialName: 'Gum arabic',
    dutchNames: ['arabische gom', 'arabischegom', 'arabische-gom'],
    functionalCategory: 'Stabilisator',
    dutchCategoryName: 'stabilisator',
    purpose: 'Verdikkingsmiddel en stabilisator uit acaciaklei',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['snoep', 'dranken', 'glazuur'],
    voedingscentrumGuidance: 'Natuurlijk verdikkingsmiddel van plantenherkomst',
  },

  E422: {
    code: 'E422',
    officialName: 'Glycerol',
    dutchNames: ['glycerol', 'glycerine', 'glycerol (glyserine)'],
    functionalCategory: 'Bevochtigingsmiddel',
    dutchCategoryName: 'vochtvasthouder',
    purpose: 'Bevochtigingsmiddel en oplosmiddel',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['bakkerij', 'snoep', 'glazuur'],
    voedingscentrumGuidance: 'Gebruikt als bevochtigingsmiddel en oplosmiddel',
  },

  // Colors continued
  E160a: {
    code: 'E160a',
    officialName: 'Carotene',
    dutchNames: ['caroteen', 'carotenen', 'caroteen (E160a)', 'beta-caroteen', 'bètacaroteen'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Natuurlijke gele/oranje kleurstof (caroteen)',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['boter', 'margarine', 'kaas'],
    voedingscentrumGuidance: 'Natuurlijke kleurstof afkomstig uit planten',
  },

  E903: {
    code: 'E903',
    officialName: 'Carnauba wax / Beeswax (Cera alba)',
    dutchNames: ['bijenwas', 'carnaubawas', 'cera alba', 'carnaubawas (e903)'],
    functionalCategory: 'Glansmiddel',
    dutchCategoryName: 'glansmiddel',
    purpose: 'Glansmiddel en beschermlaag op bijvoorbeeld fruit en snoep',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['fruit', 'snoep', 'tabletten'],
    voedingscentrumGuidance: 'Natuurlijk glansmiddel, vaak genoemd als bijenwas of carnauba',
  },

  // Colors continued
  E101: {
    code: 'E101',
    officialName: 'Riboflavin',
    dutchNames: ['riboflavine', 'vitamine b2'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Gele kleurstof, ook vitamine B2',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['zuivel', 'granen', 'groenten'],
    voedingscentrumGuidance: 'Vitamine B2, essentiële voedingsstof en natuurlijke gele kleurstof',
  },
  E127: {
    code: 'E127',
    officialName: 'Erythrosine',
    dutchNames: ['erytrosine'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Roze/rode kleurstof',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['snoep', 'gebak', 'desserts'],
    voedingscentrumGuidance: 'Kunstmatige rode kleurstof, veilig binnen ADI-grenzen',
  },

  // Preservatives (E200-E299)
  E200: {
    code: 'E200',
    officialName: 'Sorbic acid',
    dutchNames: ['sorbinezuur'],
    functionalCategory: 'Conserveermiddel',
    dutchCategoryName: 'conserveermiddel',
    purpose: 'Conserveermiddel tegen schimmels en gisten',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['kaas', 'wijn', 'brood'],
    voedingscentrumGuidance: 'Natuurlijk conserveermiddel, algemeen als veilig beschouwd',
  },
  E202: {
    code: 'E202',
    officialName: 'Potassium sorbate',
    dutchNames: ['kaliumsorbaat'],
    functionalCategory: 'Conserveermiddel',
    dutchCategoryName: 'conserveermiddel',
    purpose: 'Conserveermiddel tegen schimmels en gisten',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['wijn', 'kaas', 'brood', 'sauzen'],
    voedingscentrumGuidance: 'Veelgebruikt conserveermiddel, algemeen als veilig beschouwd',
  },
  E210: {
    code: 'E210',
    officialName: 'Benzoic acid',
    dutchNames: ['benzoëzuur'],
    functionalCategory: 'Conserveermiddel',
    dutchCategoryName: 'conserveermiddel',
    purpose: 'Conserveermiddel tegen bacteriën en schimmels',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: true,
    commonProducts: ['dranken', 'sauzen', 'jam'],
    voedingscentrumGuidance: 'Kan astma en eczeem verergeren bij gevoelige personen',
  },
  E211: {
    code: 'E211',
    officialName: 'Sodium benzoate',
    dutchNames: ['natriumbenzoaat'],
    functionalCategory: 'Conserveermiddel',
    dutchCategoryName: 'conserveermiddel',
    purpose: 'Conserveermiddel tegen bacteriën en schimmels',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: true,
    commonProducts: ['frisdranken', 'sauzen', 'jam'],
    voedingscentrumGuidance: 'Kan astma en eczeem verergeren bij gevoelige personen',
  },
  E220: {
    code: 'E220',
    officialName: 'Sulphur dioxide',
    dutchNames: ['zwaveldioxide', 'sulfiet'],
    functionalCategory: 'Conserveermiddel',
    dutchCategoryName: 'conserveermiddel',
    purpose: 'Conserveermiddel en antioxidant',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: true,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['wijn', 'gedroogd fruit', 'aardappelproducten'],
    voedingscentrumGuidance: 'Officieel allergeen, moet op etiket vermeld worden',
  },
  E223: {
    code: 'E223',
    officialName: 'Sodium metabisulphite',
    dutchNames: ['natriumdisulfiet', 'sulfiet'],
    functionalCategory: 'Conserveermiddel',
    dutchCategoryName: 'conserveermiddel',
    purpose: 'Conserveermiddel en antioxidant',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: true,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['wijn', 'gedroogd fruit', 'vleeswaren'],
    voedingscentrumGuidance: 'Officieel allergeen (sulfiet), moet op etiket vermeld worden',
  },
  E270: {
    code: 'E270',
    officialName: 'Lactic acid',
    dutchNames: ['melkzuur'],
    functionalCategory: 'Zuurteregelaar',
    dutchCategoryName: 'zuurteregelaar',
    purpose: 'Zuurteregelaar en conserveermiddel',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['zuivel', 'brood', 'vleeswaren'],
    voedingscentrumGuidance: 'Natuurlijk melkzuur, algemeen als veilig beschouwd',
  },
  E250: {
    code: 'E250',
    officialName: 'Sodium nitrite',
    dutchNames: ['natriumnitriet'],
    functionalCategory: 'Conserveermiddel',
    dutchCategoryName: 'conserveermiddel',
    purpose: 'Conserveermiddel en kleurstabilisator voor vlees',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['vleeswaren', 'bacon', 'ham'],
    voedingscentrumGuidance: 'Nitriet in vleeswaren, binnen ADI-grenzen veilig',
  },

  E282: {
    code: 'E282',
    officialName: 'Calcium propionate',
    dutchNames: ['calciumpropionaat', 'calcium propionaat'],
    functionalCategory: 'Conserveermiddel',
    dutchCategoryName: 'conserveermiddel',
    purpose: 'Conserveermiddel tegen schimmelvorming in bakkerijproducten',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['brood', 'bakkerij'],
    voedingscentrumGuidance: 'Veelgebruikt conserveermiddel in brood en bakkerijproducten',
  },

  E472e: {
    code: 'E472e',
    officialName: 'Mono- and diacetyltartaric acid esters of mono- and diglycerides of fatty acids',
    dutchNames: [
      'veresterd met monoacetyl- en diacetylwijnsteenzuur',
      'monoacetyl diacetyl wijnsteenzuur ester',
      'mono- en diacetylwijnsteenzuur esters',
    ],
    functionalCategory: 'Emulgator',
    dutchCategoryName: 'emulgator',
    purpose: 'Emulgator en broodverbeteraar (esters van vetzuren)',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['brood', 'bakkerij'],
    voedingscentrumGuidance: 'Wordt gebruikt als emulgator en verbetert de textuur van bakkerijproducten',
  },

  E481: {
    code: 'E481',
    officialName: 'Sodium stearoyl-2-lactylate / Stearoyl-2-lactylaten',
    dutchNames: ['natriumstearoyl-2-lactylaat', 'stearoyl-2-lactylaat', 'stearoyl lactilaat', 'stearoyl-lactylaat'],
    functionalCategory: 'Emulgator',
    dutchCategoryName: 'emulgator',
    purpose: 'Emulgator en meelverbeteraar in bakkerijproducten',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['brood', 'bakkerij', 'gebak'],
    voedingscentrumGuidance: 'Veelgebruikt emulgator in brood en bakkerijproducten',
  },

  E482: {
    code: 'E482',
    officialName: 'Calcium stearoyl-2-lactylate',
    dutchNames: ['calciumstearoyl-2-lactylaat', 'calcium stearoyl-2-lactylaat', 'stearoyl-2-lactylaat calcium'],
    functionalCategory: 'Emulgator',
    dutchCategoryName: 'emulgator',
    purpose: 'Emulgator en meelverbeteraar (calciumzout variant)',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['brood', 'bakkerij'],
    voedingscentrumGuidance: 'Calciumzout van stearoyl-2-lactylaat, gebruikt in bakkerijproducten',
  },

  // Antioxidants (E300-E399)
  E300: {
    code: 'E300',
    officialName: 'Ascorbic acid',
    dutchNames: ['ascorbinezuur', 'vitamine c', 'antioxidant ascorbinezuur'],
    functionalCategory: 'Antioxidant',
    dutchCategoryName: 'antioxidant',
    purpose: 'Antioxidant en vitamine C',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['fruit', 'groenten', 'sappen'],
    voedingscentrumGuidance: 'Vitamine C, essentiële voedingsstof en natuurlijke antioxidant',
  },
  E301: {
    code: 'E301',
    officialName: 'Sodium ascorbate',
    dutchNames: ['natriumascorbaat'],
    functionalCategory: 'Antioxidant',
    dutchCategoryName: 'antioxidant',
    purpose: 'Antioxidant, natriumzout van vitamine C',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['vleeswaren', 'sappen', 'conserven'],
    voedingscentrumGuidance: 'Veilige vorm van vitamine C als antioxidant',
  },
  E330: {
    code: 'E330',
    officialName: 'Citric acid',
    dutchNames: ['citroenzuur', 'voedingszuur citroenzuur'],
    functionalCategory: 'Voedingszuur',
    dutchCategoryName: 'voedingszuur',
    purpose: 'Zuurteregelaar en antioxidant',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['dranken', 'snoep', 'jam', 'conserven'],
    voedingscentrumGuidance: 'Natuurlijk citroenzuur uit citrusvruchten, zeer veilig',
  },

  E296: {
    code: 'E296',
    officialName: 'Malic acid',
    dutchNames: ['appelzuur'],
    functionalCategory: 'Voedingszuur',
    dutchCategoryName: 'voedingszuur',
    purpose: 'Zuurteregelaar en smaakversterker',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['dranken', 'snacks', 'sauzen'],
    voedingscentrumGuidance: 'Appelzuur wordt gebruikt als zuurteregelaar en smaakversterker',
  },

  // Emulsifiers & Stabilizers (E400-E499)
  E440: {
    code: 'E440',
    officialName: 'Pectin',
    dutchNames: ['pectine', 'pektine', 'pektinen', 'pektine (geleermiddel)'],
    functionalCategory: 'Geleermiddel',
    dutchCategoryName: 'geleermiddel',
    purpose: 'Geleermiddel en verdikkingsmiddel',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['jam', 'gelei', 'yoghurt'],
    voedingscentrumGuidance: 'Natuurlijke vezel uit fruit, zeer veilig',
  },

  E162: {
    code: 'E162',
    officialName: 'Beetroot Red',
    dutchNames: ['bietenrood', 'bietensap', 'bietensapconcentraat'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Rode kleurstof uit rode biet',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['sappen', 'snoep', 'sauzen'],
    voedingscentrumGuidance: 'Natuurlijke kleurstof uit bieten, algemeen als veilig beschouwd',
  },
  E471: {
    code: 'E471',
    officialName: 'Mono- and diglycerides of fatty acids',
    dutchNames: [
      'mono- en diglyceriden van vetzuren',
      'mono diglyceriden',
      'diglyceriden',
      'monodiglyceriden',
    ],
    functionalCategory: 'Emulgator',
    dutchCategoryName: 'emulgator',
    purpose: 'Emulgator voor menging van vet en water',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['brood', 'margarine', 'ijs'],
    voedingscentrumGuidance: 'Natuurlijke emulgator uit plantaardige of dierlijke vetten',
  },
  E464: {
    code: 'E464',
    officialName: 'Hydroxypropyl methylcellulose',
    dutchNames: ['hydroxypropylmethylcellulose'],
    functionalCategory: 'Stabilisator',
    dutchCategoryName: 'stabilisator',
    purpose: 'Stabilisator en verdikkingsmiddel',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['aardappelproducten', 'sauzen', 'zuivel'],
    voedingscentrumGuidance: 'Plantaardige stabilisator, toegestaan in biologische producten',
  },

  // Flavor enhancers (E600-E699)
  E621: {
    code: 'E621',
    officialName: 'Monosodium glutamate',
    dutchNames: ['mononatriumglutamaat', 'msg', 'gistextract', 'gistextractpoeder', 'gistextract'],
    functionalCategory: 'Smaakversterker',
    dutchCategoryName: 'smaakversterker',
    purpose: 'Smaakversterker voor umami-smaak',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['soepen', 'sauzen', 'chips', 'instant maaltijden'],
    voedingscentrumGuidance: 'Veilig binnen ADI-grenzen, geen bewezen gezondheidsrisicos',
  },

  // Glazing agents (E900-E999)
  E901: {
    code: 'E901',
    officialName: 'Beeswax',
    dutchNames: ['bijenwas'],
    functionalCategory: 'Glansmiddel',
    dutchCategoryName: 'glansmiddel',
    purpose: 'Glansmiddel en coating',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: true,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['snoep', 'fruit coating', 'kauwgom'],
    voedingscentrumGuidance: 'Natuurlijke bijenwas, niet geschikt voor veganisten',
  },
  E551: {
    code: 'E551',
    officialName: 'Silicon dioxide',
    dutchNames: ['siliciumdioxide', 'siliciumdioxide (antischuimmiddel)'],
    functionalCategory: 'Antiklontermiddel',
    dutchCategoryName: 'antiklontermiddel',
    purpose: 'Antiklontermiddel en antischuimmiddel',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['poeders', 'kruiden', 'smaakstoffen'],
    voedingscentrumGuidance:
      'Wordt gebruikt als antiklontermiddel en is veilig binnen gebruiksniveaus',
  },
  E950: {
    code: 'E950',
    officialName: 'Acesulfame K',
    dutchNames: ['acesulfaam k', 'acesulfaam', 'acesulfaam-k', 'acesulfaamk'],
    functionalCategory: 'Zoetstof',
    dutchCategoryName: 'zoetstof',
    purpose: 'Kunstmatige zoetstof, 200x zoeter dan suiker',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['light dranken', 'suikervrije snoep'],
    voedingscentrumGuidance: 'Kunstmatige zoetstof, veilig binnen ADI-grenzen',
  },
  E951: {
    code: 'E951',
    officialName: 'Aspartame',
    dutchNames: ['aspartaam'],
    functionalCategory: 'Zoetstof',
    dutchCategoryName: 'zoetstof',
    purpose: 'Kunstmatige zoetstof, 200x zoeter dan suiker',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: true,
    asthmaEczemaRisk: false,
    commonProducts: ['light dranken', 'suikervrije producten'],
    voedingscentrumGuidance:
      'Bevat aspartaam (een bron van fenylalanine), niet geschikt voor PKU-patiënten',
  },
  E960: {
    code: 'E960',
    officialName: 'Steviol glycosides',
    dutchNames: ['steviolglycosiden', 'stevia'],
    functionalCategory: 'Zoetstof',
    dutchCategoryName: 'zoetstof',
    purpose: 'Natuurlijke zoetstof uit stevia-plant',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['natuurlijke zoetstoffen', 'light producten'],
    voedingscentrumGuidance: 'Natuurlijke zoetstof uit stevia-plant, veilig alternatief',
  },

  E955: {
    code: 'E955',
    officialName: 'Sucralose',
    dutchNames: ['sucralose'],
    functionalCategory: 'Zoetstof',
    dutchCategoryName: 'zoetstof',
    purpose: 'Kunstmatige zoetstof',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['light dranken', 'suikervrije producten'],
    voedingscentrumGuidance: 'Kunstmatige zoetstof, veilig binnen ADI-grenzen',
  },

  // Caramel colors (E150 series) - very common in beverages and baked goods
  E150a: {
    code: 'E150a',
    officialName: 'Plain caramel',
    dutchNames: ['karamel', 'gekaramelliseerde suiker', 'karamelkleurstof'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Bruine kleurstof door verhitting van suiker',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['cola', 'bier', 'brood', 'koekjes'],
    voedingscentrumGuidance: 'Natuurlijke karamelkleurstof, algemeen als veilig beschouwd',
  },
  E150b: {
    code: 'E150b',
    officialName: 'Caustic sulphite caramel',
    dutchNames: ['sulfietkaramel', 'karamelkleurstof III'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Bruine kleurstof met sulfietbehandeling',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: true,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['bier', 'spiritus', 'azijn'],
    voedingscentrumGuidance: 'Bevat sulfiet, kan allergische reacties veroorzaken',
  },
  E150c: {
    code: 'E150c',
    officialName: 'Ammonia caramel',
    dutchNames: ['ammoniakaramel', 'karamelkleurstof III'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Bruine kleurstof met ammoniabehandeling',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['bier', 'brood', 'soja saus'],
    voedingscentrumGuidance: 'Karamelkleurstof met ammoniak, veilig binnen ADI-grenzen',
  },
  E150d: {
    code: 'E150d',
    officialName: 'Sulphite ammonia caramel',
    dutchNames: ['sulfiet-ammoniakaramel', 'karamelkleurstof IV'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Bruine kleurstof met sulfiet en ammoniak',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: true,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['cola', 'frisdranken', 'likeuren'],
    voedingscentrumGuidance: 'Bevat sulfiet, meest gebruikte karamelkleurstof in cola',
  },

  // Natural colors
  E160b: {
    code: 'E160b',
    officialName: 'Annatto',
    dutchNames: ['annatto', 'orlean', 'bixin'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Geel-oranje kleurstof uit annatto-zaden',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['kaas', 'boter', 'margarine'],
    voedingscentrumGuidance: 'Natuurlijke kleurstof uit tropische zaden',
  },
  E160c: {
    code: 'E160c',
    officialName: 'Paprika extract',
    dutchNames: ['paprika-extract', 'capsanthin', 'capsorubin'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Rode kleurstof uit paprika',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['vleeswaren', 'sauzen', 'kruiden'],
    voedingscentrumGuidance: 'Natuurlijke rode kleurstof uit paprika',
  },

  // Additional preservatives
  E212: {
    code: 'E212',
    officialName: 'Potassium benzoate',
    dutchNames: ['kaliumbenzoaat'],
    functionalCategory: 'Conserveermiddel',
    dutchCategoryName: 'conserveermiddel',
    purpose: 'Conserveermiddel tegen bacteriën en schimmels',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: true,
    commonProducts: ['frisdranken', 'sauzen', 'jam'],
    voedingscentrumGuidance: 'Kan astma en eczeem verergeren bij gevoelige personen',
  },
  E213: {
    code: 'E213',
    officialName: 'Calcium benzoate',
    dutchNames: ['calciumbenzoaat'],
    functionalCategory: 'Conserveermiddel',
    dutchCategoryName: 'conserveermiddel',
    purpose: 'Conserveermiddel tegen bacteriën en schimmels',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: true,
    commonProducts: ['frisdranken', 'sauzen', 'marinades'],
    voedingscentrumGuidance: 'Kan astma en eczeem verergeren bij gevoelige personen',
  },

  // Acidity regulators
  E500: {
    code: 'E500',
    officialName: 'Sodium carbonates',
    dutchNames: ['natriumcarbonaat', 'soda', 'natriumwaterstofcarbonaat', 'bakpoeder', 'natriumcarbonaten'],
    functionalCategory: 'Zuurteregelaar',
    dutchCategoryName: 'zuurteregelaar',
    purpose: 'Zuurteregelaar en rijsmiddel',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['bakkerij', 'koekjes', 'crackers'],
    voedingscentrumGuidance: 'Veilige zuurteregelaar, vaak gebruikt als bakpoeder',
  },
  E501: {
    code: 'E501',
    officialName: 'Potassium carbonates',
    dutchNames: ['kaliumcarbonaat', 'kaliumwaterstofcarbonaat'],
    functionalCategory: 'Zuurteregelaar',
    dutchCategoryName: 'zuurteregelaar',
    purpose: 'Zuurteregelaar en stabilisator',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['wijn', 'chocolade', 'gebak'],
    voedingscentrumGuidance: 'Natuurlijke zuurteregelaar, veilig voor consumptie',
  },

  // Phosphates - very common in processed foods
  E450: {
    code: 'E450',
    officialName: 'Diphosphates',
    dutchNames: ['difosfaat', 'dinatriumdifosfaat', 'tetrakaliumdifosfaat'],
    functionalCategory: 'Emulgator',
    dutchCategoryName: 'emulgator',
    purpose: 'Emulgator en stabilisator in vlees en zuivel',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['vleeswaren', 'kaas', 'instant producten'],
    voedingscentrumGuidance: 'Fosfaten kunnen calciumopname beïnvloeden bij hoge inname',
  },
  E451: {
    code: 'E451',
    officialName: 'Triphosphates',
    dutchNames: ['trifosfaat', 'natriumtrifosfaat'],
    functionalCategory: 'Emulgator',
    dutchCategoryName: 'emulgator',
    purpose: 'Watervasthoudend middel in vlees',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['garnalen', 'vis', 'vleeswaren'],
    voedingscentrumGuidance: 'Fosfaten, matige consumptie aanbevolen',
  },
  E452: {
    code: 'E452',
    officialName: 'Polyphosphates',
    dutchNames: ['polyfosfaat', 'natriumpolyfosfaat'],
    functionalCategory: 'Emulgator',
    dutchCategoryName: 'emulgator',
    purpose: 'Watervasthoudend en bindmiddel',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['vleeswaren', 'vis', 'kaas'],
    voedingscentrumGuidance: 'Fosfaten, matige consumptie aanbevolen',
  },

  // Cellulose derivatives
  E466: {
    code: 'E466',
    officialName: 'Carboxymethylcellulose',
    dutchNames: ['carboxymethylcellulose', 'cmc', 'natriumcarboxymethylcellulose'],
    functionalCategory: 'Stabilisator',
    dutchCategoryName: 'stabilisator',
    purpose: 'Verdikkingsmiddel en stabilisator',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['ijs', 'sauzen', 'glutenvrije producten'],
    voedingscentrumGuidance: 'Plantaardige stabilisator, veilig voor consumptie',
  },

  // Flavor enhancers
  E627: {
    code: 'E627',
    officialName: 'Disodium guanylate',
    dutchNames: ['dinatriumguanylaat', 'guanylaat'],
    functionalCategory: 'Smaakversterker',
    dutchCategoryName: 'smaakversterker',
    purpose: 'Smaakversterker, versterkt umami-smaak',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['chips', 'instant soepen', 'snacks'],
    voedingscentrumGuidance: 'Vaak gecombineerd met MSG, veilig binnen ADI-grenzen',
  },
  E631: {
    code: 'E631',
    officialName: 'Disodium inosinate',
    dutchNames: ['dinatriuminosinaat', 'inosinaat'],
    functionalCategory: 'Smaakversterker',
    dutchCategoryName: 'smaakversterker',
    purpose: 'Smaakversterker, versterkt umami-smaak',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['chips', 'instant soepen', 'snacks'],
    voedingscentrumGuidance: 'Vaak gecombineerd met MSG, veilig binnen ADI-grenzen',
  },

  // Glazing agents
  E902: {
    code: 'E902',
    officialName: 'Candelilla wax',
    dutchNames: ['candelillawas'],
    functionalCategory: 'Glansmiddel',
    dutchCategoryName: 'glansmiddel',
    purpose: 'Glansmiddel en coating',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['snoep', 'kauwgom', 'fruit coating'],
    voedingscentrumGuidance: 'Natuurlijke plantaardige was, veilig alternatief voor bijenwas',
  },
  E904: {
    code: 'E904',
    officialName: 'Shellac',
    dutchNames: ['schellak', 'gommelak'],
    functionalCategory: 'Glansmiddel',
    dutchCategoryName: 'glansmiddel',
    purpose: 'Glansmiddel en beschermlaag',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: true,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['snoep', 'fruit', 'tabletten'],
    voedingscentrumGuidance: 'Natuurlijke hars van schildluizen, niet geschikt voor veganisten',
  },

  // Sweeteners
  E965: {
    code: 'E965',
    officialName: 'Maltitol',
    dutchNames: ['maltitol'],
    functionalCategory: 'Zoetstof',
    dutchCategoryName: 'zoetstof',
    purpose: 'Suikeralcohol, bulkzoetstof',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['suikervrije snoep', 'kauwgom', 'chocolade'],
    voedingscentrumGuidance: 'Kan laxerend werken bij overmatige consumptie (>20g/dag)',
  },
  E967: {
    code: 'E967',
    officialName: 'Xylitol',
    dutchNames: ['xylitol', 'berkenboom suiker'],
    functionalCategory: 'Zoetstof',
    dutchCategoryName: 'zoetstof',
    purpose: 'Suikeralcohol, tandemail beschermend',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['suikervrije kauwgom', 'tandpasta', 'medicijnen'],
    voedingscentrumGuidance: 'Goed voor gebitsverzorging, kan laxerend werken bij overmatige consumptie',
  },

  // High-priority additions based on gap analysis

  // Acidity regulators - very common
  E338: {
    code: 'E338',
    officialName: 'Phosphoric acid',
    dutchNames: ['fosforzuur'],
    functionalCategory: 'Voedingszuur',
    dutchCategoryName: 'voedingszuur',
    purpose: 'Zuurteregelaar, zeer veel gebruikt in frisdranken',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['cola', 'frisdranken', 'processed foods'],
    voedingscentrumGuidance: 'Fosforzuur kan calciumopname beïnvloeden bij hoge inname',
  },

  // Sulfite salts - critical for allergen detection
  E221: {
    code: 'E221',
    officialName: 'Sodium sulphite',
    dutchNames: ['natriumsulfiet'],
    functionalCategory: 'Conserveermiddel',
    dutchCategoryName: 'conserveermiddel',
    purpose: 'Conserveermiddel en antioxidant',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: true,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['wijn', 'gedroogd fruit', 'aardappelproducten'],
    voedingscentrumGuidance: 'Officieel allergeen (sulfiet), moet op etiket vermeld worden',
  },
  E222: {
    code: 'E222',
    officialName: 'Sodium hydrogen sulphite',
    dutchNames: ['natriumwaterstofsulfiet', 'natriumbisulfiet'],
    functionalCategory: 'Conserveermiddel',
    dutchCategoryName: 'conserveermiddel',
    purpose: 'Conserveermiddel en antioxidant',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: true,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['gedroogd fruit', 'wijn', 'fruit sappen'],
    voedingscentrumGuidance: 'Officieel allergeen (sulfiet), moet op etiket vermeld worden',
  },
  E224: {
    code: 'E224',
    officialName: 'Potassium metabisulphite',
    dutchNames: ['kaliumdisulfiet', 'kaliummeta-bisulfiet'],
    functionalCategory: 'Conserveermiddel',
    dutchCategoryName: 'conserveermiddel',
    purpose: 'Conserveermiddel en antioxidant in wijn',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: true,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['wijn', 'bier', 'fruit sappen'],
    voedingscentrumGuidance: 'Officieel allergeen (sulfiet), moet op etiket vermeld worden',
  },

  // Additional nitrates - regulatory importance
  E251: {
    code: 'E251',
    officialName: 'Sodium nitrate',
    dutchNames: ['natriumnitraat'],
    functionalCategory: 'Conserveermiddel',
    dutchCategoryName: 'conserveermiddel',
    purpose: 'Conserveermiddel en kleurstabilisator voor vlees',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['vleeswaren', 'spek', 'ham'],
    voedingscentrumGuidance: 'Nitraat in vleeswaren, binnen ADI-grenzen veilig',
  },
  E252: {
    code: 'E252',
    officialName: 'Potassium nitrate',
    dutchNames: ['kaliumnitraat'],
    functionalCategory: 'Conserveermiddel',
    dutchCategoryName: 'conserveermiddel',
    purpose: 'Conserveermiddel en kleurstabilisator voor vlees',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['vleeswaren', 'spek', 'worst'],
    voedingscentrumGuidance: 'Nitraat in vleeswaren, binnen ADI-grenzen veilig',
  },

  // Common synthetic colors
  E133: {
    code: 'E133',
    officialName: 'Brilliant Blue FCF',
    dutchNames: ['brilliantblauw fcf', 'brillant blauw'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Synthetische blauwe kleurstof',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['dranken', 'snoep', 'ijs'],
    voedingscentrumGuidance: 'Synthetische blauwe kleurstof, veilig binnen ADI-grenzen',
  },

  // Controversial antioxidants - commonly flagged
  E320: {
    code: 'E320',
    officialName: 'Butylated hydroxyanisole (BHA)',
    dutchNames: ['bha', 'gebutyleerd hydroxyanisol'],
    functionalCategory: 'Antioxidant',
    dutchCategoryName: 'antioxidant',
    purpose: 'Synthetische antioxidant tegen ranzig worden',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['chips', 'noten', 'granen'],
    voedingscentrumGuidance: 'Synthetische antioxidant, discussie over veiligheid bij hoge doses',
  },
  E321: {
    code: 'E321',
    officialName: 'Butylated hydroxytoluene (BHT)',
    dutchNames: ['bht', 'gebutyleerd hydroxytolueen'],
    functionalCategory: 'Antioxidant',
    dutchCategoryName: 'antioxidant',
    purpose: 'Synthetische antioxidant tegen ranzig worden',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['chips', 'noten', 'granen'],
    voedingscentrumGuidance: 'Synthetische antioxidant, discussie over veiligheid bij hoge doses',
  },

  // Natural antioxidants - vitamin E family
  E306: {
    code: 'E306',
    officialName: 'Tocopherol-rich extract',
    dutchNames: ['tocoferol', 'vitamine e', 'tocoferolrijk extract'],
    functionalCategory: 'Antioxidant',
    dutchCategoryName: 'antioxidant',
    purpose: 'Natuurlijke antioxidant, vitamine E',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['oliën', 'margarine', 'noten'],
    voedingscentrumGuidance: 'Natuurlijke vitamine E, essentiële voedingsstof en antioxidant',
  },

  // Common stabilizer/gelling agent
  E401: {
    code: 'E401',
    officialName: 'Sodium alginate',
    dutchNames: ['natriumalginaat', 'alginaat'],
    functionalCategory: 'Stabilisator',
    dutchCategoryName: 'stabilisator',
    purpose: 'Verdikkingsmiddel en geleermiddel uit zeewier',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['ijs', 'yoghurt', 'sauzen'],
    voedingscentrumGuidance: 'Natuurlijk verdikkingsmiddel uit zeewier, veilig voor consumptie',
  },

  // Critical missing - very high frequency (325 occurrences)
  E170: {
    code: 'E170',
    officialName: 'Calcium carbonate',
    dutchNames: ['calciumcarbonaat', 'calcium carbonaat', 'kalk'],
    functionalCategory: 'Kleurstof',
    dutchCategoryName: 'kleurstof',
    purpose: 'Witte kleurstof en calciumverrijking',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['brood', 'zuivel', 'supplementen'],
    voedingscentrumGuidance: 'Natuurlijke calciumverrijking en witte kleurstof, zeer veilig',
  },

  // Found in ingredient analysis - medium frequency
  E509: {
    code: 'E509',
    officialName: 'Calcium chloride',
    dutchNames: ['calciumchloride'],
    functionalCategory: 'Verstevigingsmiddel',
    dutchCategoryName: 'verstevigingsmiddel',
    purpose: 'Verstevigingsmiddel en calciumverrijking',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['groenten', 'fruit', 'kaas'],
    voedingscentrumGuidance: 'Calciumchloride houdt groenten stevig, veilig voor consumptie',
  },
  E339: {
    code: 'E339',
    officialName: 'Sodium phosphates',
    dutchNames: ['natriumfosfaat', 'natriumfosfaten', 'mononatriumfosfaat'],
    functionalCategory: 'Emulgator',
    dutchCategoryName: 'emulgator',
    purpose: 'Emulgator en stabilisator, fosfaatgroep',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['vleeswaren', 'zuivel', 'instant producten'],
    voedingscentrumGuidance: 'Fosfaten kunnen calciumopname beïnvloeden bij hoge inname',
  },

  // Additional useful E-numbers found
  E385: {
    code: 'E385',
    officialName: 'Calcium disodium EDTA',
    dutchNames: ['edta', 'calcium dinatrium edta', 'ethyleendiaminetetra-azijnzuur'],
    functionalCategory: 'Antioxidant',
    dutchCategoryName: 'antioxidant',
    purpose: 'Antioxidant en metaalbinder (chelator)',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: false,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['sauzen', 'conserven', 'dranken'],
    voedingscentrumGuidance: 'EDTA voorkomt metaaloxidatie, veilig binnen ADI-grenzen',
  },
  E503: {
    code: 'E503',
    officialName: 'Ammonium carbonates',
    dutchNames: ['ammoniumcarbonaat', 'hirschhornsalt', 'bakkersalt'],
    functionalCategory: 'Rijsmiddel',
    dutchCategoryName: 'rijsmiddel',
    purpose: 'Rijsmiddel in bakkerij',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['koekjes', 'crackers', 'bakkerij'],
    voedingscentrumGuidance: 'Traditioneel rijsmiddel, veilig voor consumptie',
  },
  E262: {
    code: 'E262',
    officialName: 'Sodium acetates',
    dutchNames: ['natriumacetaat', 'azijnzure natrium'],
    functionalCategory: 'Zuurteregelaar',
    dutchCategoryName: 'zuurteregelaar',
    purpose: 'Zuurteregelaar en conserveermiddel',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['chips', 'azijn', 'sauzen'],
    voedingscentrumGuidance: 'Azijnzout, veilig zuurteregelaar',
  },

  // High-priority from production data analysis
  E326: {
    code: 'E326',
    officialName: 'Potassium lactate',
    dutchNames: ['kaliumlactaat'],
    functionalCategory: 'Zuurteregelaar',
    dutchCategoryName: 'zuurteregelaar',
    purpose: 'Zuurteregelaar en conserveermiddel',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['vleeswaren', 'sauzen', 'bakkerij'],
    voedingscentrumGuidance: 'Lactaatzout, veilig zuurteregelaar en conserveermiddel',
  },
  E331: {
    code: 'E331',
    officialName: 'Sodium citrates',
    dutchNames: ['natriumcitraat', 'natriumcitraten'],
    functionalCategory: 'Zuurteregelaar',
    dutchCategoryName: 'zuurteregelaar',
    purpose: 'Zuurteregelaar en emulgator',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['zuivel', 'dranken', 'sauzen'],
    voedingscentrumGuidance: 'Citroenzuur zout, veilig zuurteregelaar',
  },
  E267: {
    code: 'E267',
    officialName: 'Calcium lactate',
    dutchNames: ['calciumlactaat'],
    functionalCategory: 'Zuurteregelaar',
    dutchCategoryName: 'zuurteregelaar',
    purpose: 'Zuurteregelaar en calciumverrijking',
    isNaturallyOccurring: false,
    isSynthetic: true,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['zuivel', 'fruit', 'groenten'],
    voedingscentrumGuidance: 'Calciumlactaat voor zuurregeling en calciumverrijking, veilig',
  },
  E420: {
    code: 'E420',
    officialName: 'Sorbitol',
    dutchNames: ['sorbitol'],
    functionalCategory: 'Zoetstof',
    dutchCategoryName: 'zoetstof',
    purpose: 'Suikeralcohol en bevochtigingsmiddel',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['suikervrije producten', 'kauwgom', 'tandpasta'],
    voedingscentrumGuidance: 'Kan laxerend werken bij overmatige consumptie (>10g/dag)',
  },
  E460: {
    code: 'E460',
    officialName: 'Cellulose',
    dutchNames: ['cellulose', 'microcellulose'],
    functionalCategory: 'Stabilisator',
    dutchCategoryName: 'stabilisator',
    purpose: 'Verdikkingsmiddel en anti-klontermiddel',
    isNaturallyOccurring: true,
    isSynthetic: false,
    isAnimalDerived: false,
    organicPermitted: true,
    southamptonSix: false,
    isAllergen: false,
    pkuWarning: false,
    asthmaEczemaRisk: false,
    commonProducts: ['kaas', 'sauzen', 'glutenvrije producten'],
    voedingscentrumGuidance: 'Plantaardige cellulose, zeer veilig',
  },
};

export const CONSUMER_GUIDANCE: ConsumerGuidance = {
  safetyMessage: 'E-nummers kun je veilig eten en drinken',
  officialPosition: 'https://www.voedingscentrum.nl/encyclopedie/e-nummers.aspx',

  childWarningTemplate: '[name/E-number]: may affect activity or attention of children',
  pkuWarningTemplate: 'contains aspartame (a source of phenylalanine)',
  allergenWarningTemplate: 'contains sulfites',

  naturalAlternatives: {
    E621: 'gistextract',
    E951: 'stevia (E960)',
    E330: 'citroensap',
    E300: 'vitamine C uit fruit',
  },

  dutchPreferredNames: {
    E330: 'citroenzuur',
    E300: 'vitamine C',
    E440: 'pectine',
    E960: 'stevia',
  },

  categoryExplanations: {
    Kleurstof: 'Geven kleur aan voedingsmiddelen',
    Conserveermiddel: 'Voorkomen bederf door bacteriën, schimmels of gisten',
    Antioxidant: 'Voorkomen oxidatie en behouden smaak en kleur',
    Smaakversterker: 'Versterken de natuurlijke smaak van voedsel',
    Zoetstof: 'Geven zoete smaak met minder calorieën dan suiker',
    Emulgator: 'Mengen vet en water tot gladde textuur',
    Stabilisator: 'Behouden textuur en voorkomen scheiding',
    Verdikkingsmiddel: 'Maken producten dikker en romiger',
    Geleermiddel: 'Zorgen voor gelachtige textuur',
    Voedingszuur: 'Regelen de zuurgraad van producten',
    Zuurteregelaar: 'Houden de juiste pH-waarde aan',
    Glansmiddel: 'Geven glanzende coating aan producten',
    Antiklontermiddel: 'Voorkomen dat poeders gaan klonteren',
    Antischuimmiddel: 'Voorkomen schuimvorming tijdens productie',
    Bevochtigingsmiddel: 'Behouden vochtigheid in producten',
    Complexvormer: 'Binden metaalionen om oxidatie te voorkomen',
    Contrastverhoger: 'Verbeteren leesbaarheid van tekst op producten',
    Drijfgas: 'Creëren druk voor spuitbussen',
    Draagstof: 'Helpen bij het mengen en doseren van additieven',
    'Gemodificeerd zetmeel': 'Aangepast zetmeel voor specifieke eigenschappen',
    Meelverbeteraar: 'Verbeteren bakeigenschappen van meel',
    Rijsmiddel: 'Zorgen voor luchtige textuur in gebak',
    Schuimmiddel: 'Creëren schuimige textuur',
    Smeltzout: 'Helpen bij smelten en mengen van kaas',
    Verpakkingsgas: 'Beschermen voedsel in verpakking',
    Verstevigingsmiddel: 'Behouden stevigheid van fruit en groenten',
    Vulstof: 'Geven volume zonder veel calorieën',
  },

  commonMisconceptions: [
    'E-nummers zijn niet per definitie kunstmatig - veel zijn natuurlijk',
    'Natuurlijke alternatieven zijn niet automatisch gezonder dan E-nummers',
    'Alle goedgekeurde E-nummers zijn veilig binnen de ADI-grenzen',
    'E-nummers worden regelmatig opnieuw geëvalueerd door EFSA',
  ],
};

// Precompute lookup maps and sets for performance and centralized alias handling
function removeDiacritics(str: string): string {
  return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}

function addAlias(map: Map<string, string>, name: string, code: string) {
  const canonical = String(name).toLowerCase().trim();
  if (!canonical) return;
  if (!map.has(canonical)) map.set(canonical, code);

  const stripped = removeDiacritics(canonical);
  if (stripped !== canonical && !map.has(stripped)) map.set(stripped, code);

  // Conservative orthographic variant: c -> k (e.g., pectine -> pektine)
  const cToK = canonical.replace(/c/g, 'k');
  if (cToK !== canonical && !map.has(cToK)) map.set(cToK, code);
  const strippedCToK = removeDiacritics(cToK);
  if (strippedCToK !== cToK && !map.has(strippedCToK)) map.set(strippedCToK, code);
}

export const NAME_TO_ENUMBER_MAP: Map<string, string> = (() => {
  const map = new Map<string, string>();

  // From per-entry dutchNames
  for (const [code, def] of Object.entries(E_NUMBER_DATABASE)) {
    for (const name of def.dutchNames || []) {
      addAlias(map, name, code);
    }
  }

  // From consumer guidance (natural alternatives and preferred names)
  for (const [code, altName] of Object.entries(CONSUMER_GUIDANCE.naturalAlternatives || {})) {
    addAlias(map, String(altName), code);
  }
  for (const [code, prefName] of Object.entries(CONSUMER_GUIDANCE.dutchPreferredNames || {})) {
    addAlias(map, String(prefName), code);
  }

  // Generate additional conservative aliases from official fields to improve lookup
  // without editing every dutchNames entry manually.
  for (const [code, def] of Object.entries(E_NUMBER_DATABASE)) {
    // Add the official/English name as an alias (helps where Dutch name is missing)
    if (def.officialName) {
      addAlias(map, def.officialName, code);

      // Also add a variant with parenthetical content removed, e.g. "Stevia (E960)" -> "Stevia"
      const noParen = String(def.officialName)
        .replace(/\s*\([^)]*\)/g, '')
        .trim();
      if (noParen && noParen.toLowerCase() !== def.officialName.toLowerCase()) {
        addAlias(map, noParen, code);
      }
    }

    // (NOTE) avoid adding category names or generic common product words as aliases here
    // because those words frequently appear in ingredient lists and cause false positives.
  }

  return map;
})();

// Precomputed sets/arrays for quick lookups
export const SOUTHAMPTON_SIX_ENNUMBERS: string[] = Object.values(E_NUMBER_DATABASE)
  .filter((def) => def.southamptonSix)
  .map((def) => def.code);
export const SOUTHAMPTON_SIX_SET: ReadonlySet<string> = new Set(
  SOUTHAMPTON_SIX_ENNUMBERS.map((s) => s.toUpperCase()),
);

export const ALLERGENIC_ENNUMBERS: string[] = Object.values(E_NUMBER_DATABASE)
  .filter((def) => def.isAllergen)
  .map((def) => def.code);
export const ALLERGENIC_SET: ReadonlySet<string> = new Set(
  ALLERGENIC_ENNUMBERS.map((s) => s.toUpperCase()),
);

export const ANIMAL_DERIVED_ENNUMBERS: string[] = Object.values(E_NUMBER_DATABASE)
  .filter((def) => def.isAnimalDerived)
  .map((def) => def.code);
export const ANIMAL_DERIVED_SET: ReadonlySet<string> = new Set(
  ANIMAL_DERIVED_ENNUMBERS.map((s) => s.toUpperCase()),
);

export const BANNED_ENNUMBERS: string[] = Object.values(E_NUMBER_DATABASE)
  .filter((def) => def.bannedSince)
  .map((def) => def.code);
export const BANNED_SET: ReadonlySet<string> = new Set(
  BANNED_ENNUMBERS.map((s) => s.toUpperCase()),
);

// Helper functions for database lookups
export function getENumberDefinition(eNumber: string): ENumberDefinition | undefined {
  return E_NUMBER_DATABASE[eNumber.toUpperCase()];
}

export function isValidENumber(eNumber: string): boolean {
  return eNumber.toUpperCase() in E_NUMBER_DATABASE;
}

export function getENumbersByCategory(category: FunctionalCategory): ENumberDefinition[] {
  return Object.values(E_NUMBER_DATABASE).filter((def) => def.functionalCategory === category);
}

export function getSouthamptonSixENumbers(): string[] {
  return Object.values(E_NUMBER_DATABASE)
    .filter((def) => def.southamptonSix)
    .map((def) => def.code);
}

export function getAllergenicENumbers(): string[] {
  return Object.values(E_NUMBER_DATABASE)
    .filter((def) => def.isAllergen)
    .map((def) => def.code);
}

export function getAnimalDerivedENumbers(): string[] {
  return Object.values(E_NUMBER_DATABASE)
    .filter((def) => def.isAnimalDerived)
    .map((def) => def.code);
}

export function getBannedENumbers(): string[] {
  return Object.values(E_NUMBER_DATABASE)
    .filter((def) => def.bannedSince)
    .map((def) => def.code);
}
